### PR TITLE
Update triangular_144_O.md

### PR DESCRIPTION
**Pull request by mhibatallah**

### CODE REVIEW

**Comment by gcarleo** [comment]
thank you Mohamed ! why one row reports ITensor and not the link to the code? thanks!

**Comment by wdphy16** [comment]
Hi @mhibatallah , did you do something special in DMRG, like the two-site variance estimation that you once mentioned? If there was nothing special other than the default DMRG in ITensors.jl, I can just link these results to my DMRG code at https://github.com/varbench/methods/tree/main/programs/dmrg_itensors

**Comment by mhibatallah** [comment]
Thank you, Giuseppe and Dian. Indeed, I have realized that I also need to provide a link to the code, thanks for letting me know. 

For DMRG calculations on the triangular Heisenberg, I instead used the C++ version of ITensor here https://github.com/ITensor/ITensor. Since it looks like the majority of DMRG code is run on ITensor.jl, we could convert the [C++ code](http://itensor.org/docs.cgi?vers=cppv3&page=formulas/2d_dmrg) I am using to Julia. If you agree with this idea, you can find below a template of the code I am using, and feel free to modify my pull request accordingly. Otherwise, let me know if you have a better idea, thank you.

```
#include "itensor/all.h"

using namespace itensor;

int main()
    {
    int Nx = 12;
    int Ny = 12;
    auto N = Nx*Ny;
    auto yperiodic = false;

    //
    // Initialize the site degrees of freedom.
    //
    auto sites = SpinHalf(N,{"ConserveQNs=",true});

    //
    // Use the AutoMPO feature to create the
    // next-neighbor Heisenberg model.
    //
    auto ampo = AutoMPO(sites);
    auto lattice = triangularLattice(Nx,Ny,{"YPeriodic=",yperiodic});
    for(auto bnd : lattice)
        {
        ampo += 0.5,"S+",bnd.s1,"S-",bnd.s2;
        ampo += 0.5,"S-",bnd.s1,"S+",bnd.s2;
        ampo +=     "Sz",bnd.s1,"Sz",bnd.s2;
        }
    auto H = toMPO(ampo);

    // Set the initial wavefunction matrix product state
    // to be a Neel state.
    //
    // This choice implicitly sets the global Sz quantum number
    // of the wavefunction to zero. Since it is an MPS
    // it will remain in this quantum number sector.
    //
    auto state = InitState(sites);
    for(int i = 1; i <= N; ++i)
        {
        if(i%2 == 1)
            state.set(i,"Up");
        else
            state.set(i,"Dn");
        }

    auto psi0 = MPS(state);

    //
    // overlap calculates matrix elements of MPO's with respect to MPS's
    // inner(psi0,H,psi0) = <psi0|H|psi0>
    //
    printfln("Initial energy = %.5f", inner(psi0,H,psi0) );

    //
    // Set the parameters controlling the accuracy of the DMRG
    // calculation for each DMRG sweep.
    // Here less than 5 cutoff values are provided, for example,
    // so all remaining sweeps will use the last one given (= 1E-10).
    //
    auto sweeps = Sweeps(5);
    sweeps.maxdim() = 10,20,100,100,200,500,1000,2000,3000,4000;
    sweeps.cutoff() = 1E-10;
    sweeps.niter() = 2;
    sweeps.noise() = 1E-7,1E-8,0.0;
    println(sweeps);

    //
    // Begin the DMRG calculation
    //
    auto [energy,psi] = dmrg(H,psi0,sweeps,"Quiet");

    //
    // Print the final energy reported by DMRG
    //

    E = inner(psi,H,psi);
    printfln("\nGround State Energy = %.10f",energy);
    printfln("\nUsing overlap = %.10f", E );

    println("\nTotal QN of Ground State = ",totalQN(psi));

    H2 = inner(H,psi,H,psi);
    var = H2-E^2;
    println("\nEnergy variance = ",var);
    return 0;
    }

```

**Comment by wdphy16** [comment]
Actually I'm not sure if we can say the majority of DMRG code is run on ITensor.jl, and there are indeed a lot of other people using C++. I think it's better to preserve your original code used in the benchmarking, and it can be interesting to see your choices of hyperparameters like `maxdim, cutoff, niter, noise`. (Also, there seems to be a bug in your template above that you defined only 5 sweeps but more than 5 values of maxdim.)

You can upload your C++ code to the methods repo, then I can make a PR in this repo to add the links.

**Comment by mhibatallah** [comment]
That sounds good, Dian, and thank you for spotting the typo in the code. 

I started my leave this week and will be back at the end of August. I hope it is okay for you if I do it by then. Otherwise, if this is urgent, please feel free to let me know.

**Comment by gcarleo** [comment]
my understanding is that this is the last one of the very last codes missing, would appreciate if you could it sooner thanks

**Comment by wdphy16** [comment]
Thanks for your help! I've added the links in #36

**Pull request closed without merging**
